### ISSUE TITLE
comments not iterable in home.ejs

### ISSUE THREAD

**Issue by ThisisMS11** [mkarrim7/codeial#1]
I have solved the issue and also added comments for your reference. 
the issue was in home.ejs only do checkout .

![Screenshot 2023-01-07 102239](https://user-images.githubusercontent.com/91526766/211131968-fc542a11-1c83-4970-83cf-f8d22e55f723.png)
![Screenshot 2023-01-07 102528](https://user-images.githubusercontent.com/91526766/211131969-a1e45e85-3de1-423f-810f-17c9427b53bd.png)

[issue resolved code.zip](https://github.com/mkarrim7/codeial/files/10365536/issue.resolved.code.zip)

**Comment by mkarrim7** [comment]
Thank you
